---
- name: Install selinux utility packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - libsemanage-python
    - policycoreutils-python
  when: ansible_os_family == 'RedHat'
